// styles/jobCardStyles.ts

import { StyleSheet } from 'react-native';
import { FONT_SIZES, RADII, SPACING, ThemeColors } from '@/constants/theme';

export function makeStyles(c: ThemeColors) {
  return StyleSheet.create({
    outer: {
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    inner: {
      flex: 1,
      borderRadius: 24,
      backgroundColor: c.cardBg,
      overflow: 'hidden',
      padding: SPACING.lg,
      paddingBottom: SPACING.md,
      shadowColor: c.isDark ? '#000000' : '#051650',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: c.isDark ? 0.40 : 0.10,
      shadowRadius: 16,
      elevation: 4,
      borderWidth: c.isDark ? 1 : 0,
      borderColor: c.cardBorder,
    },
    companyRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: SPACING.md,
      gap: SPACING.sm,
    },
    companyLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm + 2,
    },
    companyMeta: {
      flex: 1,
    },
    companyNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.xs,
      marginBottom: 3,
    },
    companyName: {
      flex: 1,
      color: c.text,
      fontSize: FONT_SIZES.md,
      fontWeight: '700',
    },
    followBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: c.bgDeep,
      alignItems: 'center',
      justifyContent: 'center',
    },
    postedAt: {
      fontSize: FONT_SIZES.xs,
      color: c.textMuted,
    },
    rightColumn: {
      alignItems: 'flex-end',
      gap: 8,
      flexShrink: 0,
    },
    iconPair: {
      flexDirection: 'row',
      gap: 6,
    },
    iconBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: c.bgDeep,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconBtnSaved: {
      backgroundColor: 'rgba(245,158,11,0.12)',
    },
    followBtnActive: {
      backgroundColor: 'rgba(245,158,11,0.12)',
    },
    scoreBlock: {
      alignItems: 'flex-end',
    },
    scoreLabel: {
      fontSize: 9,
      fontWeight: '600',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: 2,
      color: c.textMuted,
    },
    scoreNumberRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 1,
    },
    scoreNumber: {
      color: c.text,
      fontSize: 30,
      fontWeight: '800',
      letterSpacing: -0.5,
      lineHeight: 32,
    },
    scorePercent: {
      color: c.text,
      fontSize: 14,
      fontWeight: '600',
    },
    scoreBarBg: {
      marginTop: 3,
      width: 70,
      height: 3,
      borderRadius: 2,
      backgroundColor: c.isDark ? 'rgba(255,255,255,0.10)' : 'rgba(5,22,80,0.10)',
      overflow: 'hidden',
    },
    scoreBarFill: {
      height: 3,
      borderRadius: 2,
      backgroundColor: c.isDark ? 'rgba(255,255,255,0.45)' : c.text,
    },
    seniorityChip: {
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderRadius: RADII.full,
      paddingHorizontal: 10,
      paddingVertical: 5,
      marginTop: SPACING.md,
      marginBottom: SPACING.sm,
      backgroundColor: c.isDark ? 'rgba(255,255,255,0.07)' : 'rgba(5,22,80,0.07)',
      borderColor: c.cardBorder,
    },
    seniorityChipText: {
      fontSize: 10.5,
      fontWeight: '600',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      color: c.text,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 4,
      marginTop: 10,
      marginBottom: SPACING.md + 4,
    },
    title: {
      flex: 1,
      color: c.text,
      fontSize: 24,
      fontWeight: '800',
      letterSpacing: -0.5,
      lineHeight: 27,
    },
    titleChevron: {
      marginTop: 6,
      flexShrink: 0,
    },
    locationPill: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: c.bgDeep,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginBottom: SPACING.md,
      gap: 10,
      borderWidth: c.isDark ? 1 : 0,
      borderColor: c.cardBorder,
    },
    locationIconBox: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: c.accent,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    locationCity: {
      color: c.text,
      fontSize: FONT_SIZES.sm,
      fontWeight: '700',
    },
    profileMatchBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
      backgroundColor: c.isDark ? 'rgba(226,232,245,0.07)' : 'rgba(5,22,80,0.06)',
      borderRadius: RADII.full,
      paddingVertical: 6,
      paddingHorizontal: 12,
      marginBottom: SPACING.sm,
      borderWidth: 1,
      borderColor: c.isDark ? 'rgba(226,232,245,0.15)' : 'rgba(5,22,80,0.12)',
    },
    profileMatchBadgeText: {
      color: c.isDark ? c.text : c.accent,
      fontSize: FONT_SIZES.xs,
      fontWeight: '600',
    },
  });
}
